# Generated by Django 3.1.2 on 2020-10-15 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='recipe_images', verbose_name='Picture')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Recipes',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('step_number', models.IntegerField(verbose_name='Number of the step')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='step_images', verbose_name='Picture')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='step_in_recipe', to='webapp.recipe', verbose_name='Recipe')),
            ],
            options={
                'verbose_name_plural': 'Steps',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_in_recipe', to='webapp.Tag', verbose_name='Tag'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('quantity', models.TextField(blank=True, max_length=100, null=True, verbose_name='Quantity')),
                ('unit', models.CharField(choices=[('gr', 'gramm'), ('cup', 'cup'), ('ml', 'ml')], max_length=20, verbose_name='Unit')),
                ('is_deleted', models.BooleanField(default=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredient_in_recipe', to='webapp.recipe', verbose_name='Recipe')),
            ],
            options={
                'verbose_name_plural': 'Ingredients',
            },
        ),
    ]
