# Generated by Django 3.1.2 on 2020-10-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20201015_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
    ]
