# Generated by Django 3.1.2 on 2020-11-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_step_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('gr', 'gramm'), ('cup', 'cup'), ('ml', 'ml'), ('pc', 'pc'), ('kg', 'kg'), ('tbs', 'tbs'), ('ts', 'ts'), ('oz', 'ounce'), ('lbs', 'pound'), ('gal', 'gallon'), ('pinch', 'pinch')], max_length=20, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
