# Generated by Django 3.1.2 on 2020-12-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20201201_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cooking time'),
        ),
    ]
