# Generated by Django 3.1.2 on 2020-12-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_recipe_cook_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='About user'),
        ),
    ]
