# Generated by Django 3.1.2 on 2020-12-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='media/user_default.jpg', null=True, upload_to='user_images', verbose_name='Picture'),
        ),
    ]
